### ISSUE TITLE
[Bug] Gas Level Emitter has Fluid Level Emitter GUI

### ISSUE THREAD

**Issue by Ligraph** [ExtraCells/ExtraCells2#590] opened 2018-08-12 21:59 UTC
When placed and opened, the Gas Level Emitter has the GUI of the Fluid Level Emitter (and only accepts fluids).

**Comment by philomelus** [comment] 2018-08-19 10:46
Duplicate of #520

**Closed as completed** 2018-08-20 08:54 UTC
Labels: duplicate
