### ISSUE TITLE
AE2 rv4-stable-1 released...

### ISSUE THREAD

**Issue by AlexPlus117** [ExtraCells/ExtraCells2#448] opened 2017-07-24 11:19 UTC
Hi, finally rv4 stable build has been released yesterday. According to what you promised, will we see an Extra Cells update for 1.10.2 soon? I absolutely don't want to annoy you, but I'm here just to notice that AE2 is out of alpha now...

**Comment by Nedelosk** [comment] 2017-08-10 15:46
Duplicate of #438

**Closed as completed by Nedelosk** 2017-08-10 15:46 UTC
Labels: duplicate, question
