### ISSUE TITLE
Crash on Initialization of client when updating to rv6 (NoSuchMethodError)

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#611] opened 2018-10-18 11:01 UTC
https://paste.dimdev.org/bayigokumi.mccrash

```
java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
    at extracells.item.storage.ItemStorageCell.addInformation(ItemStorageCell.java:48)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
    at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
    at net.minecraft.client.util.SearchTree.index(SourceFile:49)
    at net.minecraft.client.util.SearchTree.add(SourceFile:44)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:589)
    at net.minecraft.client.Minecraft.init(Minecraft.java:528)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

That second line on pastebin, it's not me, it's [VanillaFix](https://minecraft.curseforge.com/projects/vanillafix) author jokes. :|

**Comment by Nedelosk** [comment] 2018-10-18 12:40
Duplicate of #578

**Closed as completed by Nedelosk** 2018-10-18 12:40 UTC
Labels: duplicate
