### ISSUE TITLE
[1.12.2] fluid level emitters broken + fluid storage monitors are laggy when you look at them

### ISSUE THREAD

**Issue by ghost** [ExtraCells/ExtraCells2#541] opened 2018-03-06 20:28 UTC
I have 2 problems. 

1: fluid level emitters are broken. not sure exactly what is wrong with it but its not doing what its supposed to do
2: when i look at fluid storage monitors they make my FPS drop a LOT. and if i have a lot of them like 10 together they make the FPS go down to 3-5 whether you look at them or not

this will show you what my problems are 
https://imgur.com/a/Ri0F1

**Comment by xBlizzDevious** [comment] 2018-03-12 03:23
Also having the same issue with level emitters - playing on All The Mods 3 V5.8.

Haven't had an issue with the storage monitors though I don't use them!


EDIT: This is showing up in server window:
```
[03:19:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[minecraft_server.1.12.2.jar:?]
        at extracells.part.fluid.PartFluidLevelEmitter.syncClientGui(PartFluidLevelEmitter.java:237) ~[PartFluidLevelEmitter.class:?]
        at extracells.network.packet.part.PacketPartConfig$HandlerServer.onPacketData(PacketPartConfig.java:138) ~[PacketPartConfig$HandlerServer.class:?]
        at extracells.network.PacketHandler.lambda$checkThreadAndEnqueue$1(PacketHandler.java:124) ~[PacketHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by BrockWS** [comment] 2018-04-28 07:06
I am unable to reproduce the Fluid Storage Monitor or the Fluid Level Emitter issue. Please update to use the latest AE2 and EC2. 
I have fixed the NullPointerException in the server log and will be fixed in the next build

**Closed as completed** 2018-04-28 11:46 UTC

**Comment by ghost** [comment] 2018-04-28 14:42
@BrockWS it got fixed in the newest update from the other day
