### ISSUE TITLE
Pre Configured Cells Of Liquid Xp Became "null"

### ISSUE THREAD

**Issue by RoloEdits** [ExtraCells/ExtraCells2#246] opened 2015-06-26 03:12 UTC
I Preconfigured A Cell For Liquid XP And After It Not Working With Exporting And importing I Put It Back In The Cell Workbench And Discovered The XP Became "null 6594:275"

**Comment by ruifung** [comment] 2015-08-19 12:37
Which mod is LXP from again?

**Comment by XFactHD** [comment] 2015-08-19 12:52
OpenBlocks

**Comment by XFactHD** [comment] 2015-08-19 12:55
I think the problem is that EC2 seems to instantiate the fluids (when you hover over the fluid in a preconfigured cell in the cell workbench it says extra cells as the mod in the tooltip) and as soon as you move some mods around or update them and some ids change, the filter is broken.

**Comment by ruifung** [comment] 2015-08-19 14:42
Well.. I haven't got to that part yet in my cleanup branch, I'm mainly going around and getting the base classes done first.

**Comment by XFactHD** [comment] 2015-09-28 05:30
I looked at ECs code again and it seems that a AEFluidStack is used to make the filter meaning that there is a bug in the AEFluidStack. Could you take a look @thatsIch / @yueh if I am right or if I just looked at the wrong spot.

**Comment by ruifung** [comment] 2015-09-28 06:04
Actually, this _probably_ doesn't have anything to do with how that works though.
Also what spot were you looking at? 

I think the actual cause, is the way the fluid name is shown.

```
    public String getItemStackDisplayName(ItemStack stack) {
        Fluid fluid = FluidRegistry.getFluid(stack.getItemDamage());
        if (fluid == null || fluid.getBlock() == null)
            return "null";
        Item item = Item.getItemFromBlock(fluid.getBlock());
        if (item == null)
            return "null";
        return item.getItemStackDisplayName(new ItemStack(item));
    }
```

null would be the expected result for fluids without a block implementation.

As for why it only happens after closing and reopening it? I'm not sure though...

I might port over the version of the fluid placeholder item I wrote for my rewrite branch.. at least it shows something more meaningful then "null" if it cant get the name.

**Comment by XFactHD** [comment] 2015-09-28 07:36
For fluids that don't have a fluid block that is right.
But what I meant was the second problem of the fluid filters, the fact that after updating / adding / removing mods, the fluid filter is completely messed up. An example: I have pneumaticcraft and I am storing LPG, Diesel, Kerosene and Fuel (Gasoline) in Fluid Storage Cells. After adding Ex Nihilo to the pack (it only adds one fluid) the filters are completely messed up, the Kerosene cell's filter is now LPG and other weird combinations.

**Comment by ruifung** [comment] 2015-09-28 07:48
Well yeah, it changes the fluid id's, the current version of EC2 depends a. lot. on using FluidID to store data - hence the rewrite branch - which changes how the placeholder items functions to use the fluid name and a NBT tag instead of fluidID - which will not be constant. Heck, as far as I can tell, fluidID's can not be assumed to be consistent across game restarts as its assigned everytime at start to whichever mod registers their fluids first.

**Comment by XFactHD** [comment] 2015-09-28 08:16
If you are working on a fix, that's awesome. I would really love to help you but I am just on my way of learning java and scala pretty much fucks up my brain.

**Comment by ruifung** [comment] 2015-09-28 08:45
A fixed version of the preformat filters is already in the rewrite branch - I pretty much rewrote the whole thing.

Also, once you learn scala you'll find that its pretty fun to use... except in certain situations involving generics and unparameterized stuff.

**Closed as completed** 2018-07-20 03:24 UTC
Labels: bug, investigate, awaiting-reply, triaged
