### ISSUE TITLE
[1.12.2] Crash after some time of OreDictionary Export Bus using

### ISSUE THREAD

**Issue by danzio** [ExtraCells/ExtraCells2#609] opened 2018-10-13 17:59 UTC
Hey, I have crashes after some time of using OreDictionary Export Bus. Here is crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  LoadingPlugin (noRecipeBook_v1.1.0formc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.6.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
  Wizardry Plugin (wizardry-0.9.6.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/13/18 8:21 PM
Description: Ticking GridNode

java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:499)
	at extracells.part.PartOreDictExporter.isItemValid(PartOreDictExporter.java:71)
	at extracells.part.PartOreDictExporter.doWork(PartOreDictExporter.java:166)
	at extracells.part.PartOreDictExporter.tickingRequest(PartOreDictExporter.java:388)
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:92)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:226)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1309_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:499)
	at extracells.part.PartOreDictExporter.isItemValid(PartOreDictExporter.java:71)
	at extracells.part.PartOreDictExporter.doWork(PartOreDictExporter.java:166)
	at extracells.part.PartOreDictExporter.tickingRequest(PartOreDictExporter.java:388)

-- PartOreDictExporter being ticked. --
Details:
	CurrentTickRate: 20
	MinTickRate: 1
	MaxTickRate: 20
	MachineType: extracells.part.PartOreDictExporter
	GridBlockType: extracells.gridblock.ECBaseGridBlock
	ConnectedSides: [INTERNAL]
	Location: dimension=0, x=-1110, y=54, z=932
Stacktrace:
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:92)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:226)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1309_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASM

EventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

[crash-2018-10-13_20.21.37-server.txt](https://github.com/ExtraCells/ExtraCells2/files/2475697/crash-2018-10-13_20.21.37-server.txt)

**Comment by BrockWS** [comment] 2018-12-09 13:44
Duplicate of #563. Update to newer version. Sorry for the duplicate version numbers and delay (https://minecraft.curseforge.com/projects/extracells2/files/2574581)

**Closed as completed** 2018-12-12 08:23 UTC
Labels: duplicate
