### ISSUE TITLE
AE 2 Conflict

### ISSUE THREAD

**Issue by CarlucciMods** [ExtraCells/ExtraCells2#598] opened 2018-09-26 02:02 UTC
java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1931/1085954667.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1951/189051241.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1931/1085954667.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1951/189051241.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

**Comment by BrockWS** [comment] 2018-09-26 03:38
Duplicate of #578

**Closed as completed** 2018-09-26 08:12 UTC
