### ISSUE TITLE
Crash, StackOverflowError: Ticking Gridnode

### ISSUE THREAD

**Issue by NielsPilgaard** [ExtraCells/ExtraCells2#634] opened 2019-01-13 18:23 UTC
Server crash when placing a Fluid Cell into an ME Chest. The Fluid in the Cell should have been going to the Export Bus causing the first [crash](https://gist.github.com/NillerMedDild/a72bfc4dbe242da9ab3440ef18240341). After the Export Bus was removed with MCEdit, a Fluid Interface connected to the same AE system caused a [similar crash](https://gist.github.com/xoxfaby/ef35fda9fd52c5abbffc4b7b8184b367). Removing the Fluid Interface with MCEdit allowed the server to load back up.

### Versions
- Forge 1.12.2-14.23.5.2781
- appliedenergistics2-rv6-stable-6
- ExtraCells-1.12.2-2.6.2a

**Comment by xoxfaby** [comment] 2019-01-14 01:57
I would venture a guess that it's due to the ME Chest not handling fluid chests with amounts higher than what is possible with normal fluid cells, but I'm not feeling like crashing my server any more to test it.

**Comment by BrockWS** [comment] 2019-01-14 05:11
Nothing to do with amounts. The ME Chest is telling the cell to save but the cell is telling the chest to save, causing a loop. I had forgotten to fix this when AE2 devs changed the way the saving works.

**Comment by ruifung** [comment] 2019-01-23 10:25
Also, I believe this is a dupe of #610

**Comment by BrockWS** [comment] 2019-01-26 15:24
I've rewritten the entire cell handling. The following dev build should fix the issue. Please read the notice. https://ci.brock.pw/job/ExtraCells2/job/ExtraCells2-RV6/7/

**Comment by ruifung** [comment] 2019-02-01 13:57
Closing as duplicate.

**Closed as completed by ruifung** 2019-02-01 13:57 UTC
Labels: bug, duplicate
