### ISSUE TITLE
[1.12.2] ME Gas Storage Bus is a Fluid Storage Bus

### ISSUE THREAD

**Issue by NgLoader** [ExtraCells/ExtraCells2#606] opened 2018-10-07 17:50 UTC
Hi,

The ME Gas Storage Bus is a Fluid Storage Bus when you interact with it (not work with ME Interface)

I'm using 2 ME System witch a linked with ME Interfaces and ME Storage Bus
Its work with ME Storage Bus and ME Fluid Storage Bus

Versions:
AE2: appliedenergistics2-rv6-beta-1
ExtraCells2: ExtraCells-1.12.2-2.6.1a

![Picture](https://i.imgur.com/peAKhVY.png)

[Here is a gif GIF](https://gfycat.com/FragrantWideeyedLangur)

**Comment by nowifi4u** [comment] 2018-12-05 20:56
Same goes to the ME Gas Level Emitter: 
Note: The issue is not in the name only. The Level Emitter is accepting fluids only, not the gasses.
![image](https://user-images.githubusercontent.com/36640388/49543388-28c70480-f8e9-11e8-9f0a-08aecabef379.png)
![image](https://user-images.githubusercontent.com/36640388/49543408-367c8a00-f8e9-11e8-9a5d-45cab4e4c693.png)

**Comment by BrockWS** [comment] 2018-12-10 06:48
@nowifi4u Can you please create a new issue for that.

**Comment by BrockWS** [comment] 2018-12-10 07:14
@NgLoader From what I can see there are two issues.
1. The Gas Storage Bus has the wrong name (should still function as normal)
2. The Gas Storage Bus doesn't support the capability for sharing between networks.

The name is already fixed in dev. I will see what I can do about adding the capability but it may require a small rewrite with how the gas storage bus handler works.

**Closed as completed** 2018-12-23 10:06 UTC
Labels: bug
