### ISSUE TITLE
Crash when putting 1024k Storage cell in ME Drive

### ISSUE THREAD

**Issue by Coding-Kiwi** [ExtraCells/ExtraCells2#596] opened 2018-08-28 15:25 UTC
My server crashed when I put a 1024k Storage Cell into a ME Drive, I had to delete the block to get the server running again.

Here is the crash report: [https://pastebin.com/egt9E3Hv](https://pastebin.com/egt9E3Hv)

**Comment by BrockWS** [comment] 2018-08-29 04:45
Extra Cells does not currently support AE2 rv6+

**Comment by ruifung** [comment] 2018-08-30 12:52
Duplicate of #578.

**Closed as completed by ruifung** 2018-08-30 12:52 UTC
Labels: duplicate
