### ISSUE TITLE
Crash with new Wireless Crafting Terminal library

### ISSUE THREAD

**Issue by rainbowskydancer** [ExtraCells/ExtraCells2#624] opened 2018-12-24 19:53 UTC
Pastebinning crash report here: https://pastebin.com/Kw06YaTc

Clients crashes totally to launcher. Seems WCT changed some API thing so extra cells goes "ohmegerd where's the library?!"

**Comment by rainbowskydancer** [comment] 2018-12-24 19:57
(sorry about PEBKAC I hit enter instead of shift when writing the report up...)

**Comment by BrockWS** [comment] 2018-12-25 06:47
Duplicate of #619. You can use the build located here until its up on CF. https://ci.brock.pw/job/ExtraCells2/job/ExtraCells2-RV6/4/

**Closed as completed** 2018-12-26 03:29 UTC
Labels: duplicate
