### ISSUE TITLE
Crash on loading: "NoSuchMethodError: "

### ISSUE THREAD

**Issue by Wissi** [ExtraCells/ExtraCells2#585] opened 2018-07-28 22:29 UTC
If I remove the mod everything works fine.

Full crashlog is here:  https://gist.github.com/Wissi/c1fbc182515b6c16a2755db721a25b8f

```
java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
```
```
-- Head --
Thread: Client thread
Stacktrace:
	at extracells.item.storage.ItemStorageCell.func_77624_a(ItemStorageCell.java:48)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
```

**Comment by ruifung** [comment] 2018-07-29 02:10
Duplicate of #578

**Closed as completed by ruifung** 2018-07-29 02:10 UTC
