### ISSUE TITLE
Possible cause of minecraft error

### ISSUE THREAD

**Issue by LovableJesus** [ExtraCells/ExtraCells2#600] opened 2018-09-30 15:57 UTC
Hi all, just built up a galacticraft modpack to my liking, finally about to start after handpicking the mod i wanted, and i get a error message saying "An error during startup prevented Minecraft from starting. The following mod(s) have been identified as potential causes: Extra Cells 2. Unfortuneately, it is not possible to keep loading minecraft after this error"
Any help with this would be helpful as this is the first time building up a modpack so not 100% what im doing yet.
This is the report that was generated:
https://paste.dimdev.org/xaluducila.mccrash
Thanks, LovableJesus

**Comment by Nedelosk** [comment] 2018-09-30 20:25
Duplicate of #578

**Closed as completed by Nedelosk** 2018-09-30 20:25 UTC
Labels: duplicate
