### ISSUE TITLE
Friend cant join lan world, FML Mod Regection

### ISSUE THREAD

**Issue by Aaeru1022** [ExtraCells/ExtraCells2#362] opened 2016-01-06 02:35 UTC
i run a mod pack and my friend and i play together. I hosting a lan world and she connecting to me.
one day we were running an older version of extra cells and once i began using blocks from your mod she began to crash repeatedly with tessellating errors pointing to extra cells.

so i updated both her and i to ExtraCells-1.7.10-2.3.7b176 
now she can not connect to my lan world. her screen shows "Mod rejections [FMLMod:extracells{2.3.7}]"

my console shows:

[19:20:36] [User Authenticator #2/INFO]: UUID of player Th3GreenBanana is fcedc688-668f-492c-8beb-9967a32a7a2a
[19:20:36] [Netty IO #5/INFO] [FML]: Client protocol version 2
[19:20:36] [Netty IO #5/INFO] [FML]: Client attempting to join with 161 mods : (REMOVED TO CONSERVE SPACE)
[19:20:36] [Netty IO #5/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[19:20:36] [Netty IO #5/INFO] [FML]: Rejecting connection CLIENT: [FMLMod:extracells{2.3.7}]
[19:20:36] [Server thread/INFO]: Th3GreenBanana lost connection: TextComponent{text='Mod rejections [FMLMod:extracells{2.3.7}]', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:20:36] [Server thread/INFO]: Th3GreenBanana left the game
[19:20:36] [Client thread/INFO]: [CHAT] Th3GreenBanana left the game

I am not sure what to do.

**Comment by Aaeru1022** [comment] 2016-01-06 02:37
just tested: same thing happens with a fresh world

**Comment by XFactHD** [comment] 2016-01-06 06:17
Do you both have the exact same version of ExtraCells installed?

**Comment by Aaeru1022** [comment] 2016-01-06 06:39
yes

**Comment by XFactHD** [comment] 2016-01-06 06:46
Can you try setting up a server locally (that's better than LAN hosting anyway) and try to reproduce this?

**Comment by Aaeru1022** [comment] 2016-01-06 07:25
yes but it will take some time I'll let you know when I'm done

**Comment by Aaeru1022** [comment] 2016-01-06 10:30
I have made a forge server running on my friends pc and I could connect to it just fine. However I would still really appreciate you looking into the LAN world problem as running the server and client on one pc is quite lagy.

**Comment by XFactHD** [comment] 2016-01-06 11:36
First I have to tell you that I am just someone who tries to be helpful and I am not one of the developers.
In terms of LAN worlds, they are actually a really bad hack as you are creating multiple instances of EntityPlayer which is only supposed to be instantiated once. Only EntityPlayerMP is supposed to be instantiated multiple times in one world. Conclusion: It's always better to use a local server instead of making a LAN world.

**Comment by Aaeru1022** [comment] 2016-01-06 12:33
Thank you for being someone who tries to be helpful :)
Do you have any tips for reducing the server's load on my pc so that my client doesn't lag so much?

**Comment by XFactHD** [comment] 2016-01-06 13:21
How much RAM does your computer have? I for example am playing with about 200 mods and allocated 10 GB to MC (I have 32 GB which is probably a bit overkill) and it works perfectly.

**Comment by Aaeru1022** [comment] 2016-01-06 22:11
i have 161 mods 16Gb RAM Intel i7 2600 4 cores 8 threads 3.5GHz CPU.
The client+windows 10 takes 10Gb RAM max when in use
not sure yet what the server takes.

**Comment by XFactHD** [comment] 2016-01-06 22:14
You could try 6 GB for the client and 8 GB for the server.

**Comment by Aaeru1022** [comment] 2016-01-06 22:35
Why limit the client?

**Comment by spannerman79** [comment] 2016-01-06 22:38
@Aaeru1022 I'd say this is outside the scope of this issue tracker.

This is an issue within your modpack or how you distribute your modpack.

I have (currently) 7 people connected (not including myself) to my server, with ExtraCells2 (plus another 200 odd mods) and there is no mod rejections.

@DrummerMC should close this issue.  User sided issue/error.

**Comment by XFactHD** [comment] 2016-01-06 23:07
The server needs to get more RAM than then the client because it needs to do the whole work and the client more or less just renders everything.

**Closed as completed** 2017-10-09 12:13 UTC
