### ISSUE TITLE
fluid export bus deleted acceleration upgrades after breaking it down with a pickaxe

### ISSUE THREAD

**Issue by saeschwerki** [ExtraCells/ExtraCells2#287] opened 2015-08-30 21:33 UTC
fluid export bus deleted acceleration upgrades after breaking it down with a pickaxe

**Comment by ruifung** [comment] 2015-08-31 02:30
This shouldn't be too hard to fix, I'll try to fix it when I have time to.

**Comment by ruifung** [comment] 2015-09-03 05:15
@saeschwerki  does this still happen with the latest build from jenkins?

**Comment by p-schneider** [comment] 2015-09-08 15:59
Now you can dupe items (buckets) by wrenching a ME Fluid Terminal because the item is dropped and also stays in the inventory.

**Comment by ruifung** [comment] 2015-09-08 23:34
Hmm.. missed that.

**Comment by ruifung** [comment] 2015-09-10 02:28
@p-schneider Just to be certain, its the GUI doesn't close, allowing for dupe right?

**Comment by ruifung** [comment] 2015-09-10 03:46
Side effects of original fix should be fixed now.

**Comment by p-schneider** [comment] 2015-09-10 07:20
@ruifung the dupe bug I was talking about is still there.
If you have an empty bucket in the ME Fluid Interface Slot and you close the interface the bucket stays in the interface and is stored in the inventory NBT tag.
Breaking it with a pickaxe would correctly drop the Fluid Interface itself and also the empty bucket in it.
If you break the ME Fluid Interface with a wrench (Sneak + Right Click) the bucket gets dropped once on the floor and also stays in the inventory NBT tag of the ME Fluid Interface. If you place the wrenched Interface again you will find your duped empty bucket in it.
A line like `if (wrenched) return;` as the beginning of `public void getDrops( List<ItemStack> drops, boolean wrenched)` should fix that. I haven't tried the other Blocks / Parts, but I assume those work the same.

**Comment by ruifung** [comment] 2015-09-10 08:49
OH. I SEE. (I thought its the inventory not closing.)

**Comment by ruifung** [comment] 2015-09-10 09:03
Athough I'm trying to figure how to get it to not save the inventory when being wrenched, =/
Like AE2.

**Comment by ruifung** [comment] 2015-09-11 03:20
Can you try it now to see if it still dupes?

**Comment by p-schneider** [comment] 2015-09-11 06:14
No dupes, but crashes :-(

Wrenching works fine now, however using the Pickaxe crashes the game. (Regardless if there is an item in the interface or not.)

```
java.lang.NullPointerException: Ticking memory connection
    at extracells.part.PartFluidTerminal.getItemStack(PartFluidTerminal.java:76)
    at appeng.parts.CableBusContainer.getDrops(CableBusContainer.java:1098)
    at appeng.tile.networking.TileCableBus.getDrops(TileCableBus.java:198)
    at appeng.block.AEBaseTileBlock.func_149749_a(AEBaseTileBlock.java:159)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.minecraft.world.World.func_147468_f(World.java:573)
    at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
    at appeng.block.networking.BlockCableBus.removedByPlayer(BlockCableBus.java:208)
(...)
```

I only tested it with the ME Fluid Terminal, and I haven't tried the other Blocks / Parts this time. (If it hadn't crashed I would have tested the other parts, but restarting after every try takes too much time.)

**Comment by ruifung** [comment] 2015-09-11 09:22
I really got to re setup my instance to actually test this. >.<
Anyway, in the meantime thanks for helping me test it since I can't really test it in person right now.

There we go, should fix the crash due to an oversight of mine. Heh, I whipped up the fix in between classes.

**Comment by p-schneider** [comment] 2015-09-11 10:09
I can confirm ExtraCells-1.7.10-2.2.74b140 fixed the crashes, items are no longer duped. Wenching and destroying (pickaxe) works as excepted.
I tested with the following parts:
- ME Fluid Terminal :heavy_check_mark:
- ME Fluid Export Bus :heavy_check_mark:
- ME Fluid Import Bus :heavy_check_mark:
- ME Fluid Storage Bus :heavy_check_mark:

I think this issue can now be closed :+1:
Over and out :no_entry_sign:

**Closed as completed** 2015-09-11 11:22 UTC
Labels: bug
