### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by LocalBoomer** [ExtraCells/ExtraCells2#587] opened 2018-08-01 16:09 UTC
https://pastebin.com/x9XE4myC

It says blame you :P

MC 1.12.2
Forge 14.23.4.2745
AE2 RV6 alpha 3

let me know if you need more

**Comment by BrockWS** [comment] 2018-08-02 04:04
Duplicate of #578

**Closed as completed** 2018-08-02 11:42 UTC
