### ISSUE TITLE
Crash Report for This Mod

### ISSUE THREAD

**Issue by TorinnTheDragon** [ExtraCells/ExtraCells2#597] opened 2018-09-08 05:16 UTC
- Minecraft version: 1.12.2
- Mod version: 1.12.2-2.5.13 (latest)
- Minecraft Forge version: forge-14.23.4.2760
- Modpack: Personal (WIP)

When I update all the mods including Extra Cells. Minecraft instantly crashes with this error, 
( https://pastebin.com/JCMJvAbm ).
So I hope you can figure out a fix for this crash I will have to revert all the way to mod version 1.12.2-2.5.13a56 because this was the mod version that worked before I updated to the latest update.

Thanks,
Wil

**Comment by BrockWS** [comment] 2018-09-08 05:40
Duplicate of #578.
Extra Cells does not currently support ae2 rv6-alpha.

**Closed as completed** 2018-09-08 11:56 UTC
Labels: duplicate
